export const AIRLINE_NAMES: Record<string, string> = {
  // North America
  "AC": "Air Canada",
  "WS": "WestJet",
  "TS": "Air Transat",
  "PD": "Porter Airlines",
  "F8": "Flair Airlines",
  "AA": "American Airlines",
  "DL": "Delta Air Lines",
  "UA": "United Airlines",
  "WN": "Southwest Airlines",
  "B6": "JetBlue Airways",
  "AS": "Alaska Airlines",
  "NK": "Spirit Airlines",
  "F9": "Frontier Airlines",
  "G4": "Allegiant Air",
  "SY": "Sun Country",
  "HA": "Hawaiian Airlines",
  // Mexico
  "AM": "Aeromexico",
  "Y4": "Volaris",
  "4O": "Interjet",
  // Europe
  "BA": "British Airways",
  "AF": "Air France",
  "LH": "Lufthansa",
  "KL": "KLM",
  "IB": "Iberia",
  "AZ": "ITA Airways",
  "SK": "SAS",
  "AY": "Finnair",
  "TP": "TAP Portugal",
  "EI": "Aer Lingus",
  "LX": "Swiss International",
  "OS": "Austrian Airlines",
  "SN": "Brussels Airlines",
  "DY": "Norwegian Air",
  "FR": "Ryanair",
  "U2": "easyJet",
  "W6": "Wizz Air",
  "VY": "Vueling",
  "PC": "Pegasus Airlines",
  "TK": "Turkish Airlines",
  // Middle East
  "EK": "Emirates",
  "QR": "Qatar Airways",
  "EY": "Etihad Airways",
  "GF": "Gulf Air",
  "WY": "Oman Air",
  "SV": "Saudia",
  "LY": "El Al",
  "RJ": "Royal Jordanian",
  // Asia
  "SQ": "Singapore Airlines",
  "CX": "Cathay Pacific",
  "NH": "ANA",
  "JL": "Japan Airlines",
  "KE": "Korean Air",
  "OZ": "Asiana Airlines",
  "TG": "Thai Airways",
  "MH": "Malaysia Airlines",
  "PR": "Philippine Airlines",
  "GA": "Garuda Indonesia",
  "VN": "Vietnam Airlines",
  "CI": "China Airlines",
  "BR": "EVA Air",
  "CA": "Air China",
  "MU": "China Eastern",
  "CZ": "China Southern",
  "HU": "Hainan Airlines",
  "AI": "Air India",
  // Oceania
  "QF": "Qantas",
  "VA": "Virgin Australia",
  "NZ": "Air New Zealand",
  "FJ": "Fiji Airways",
  // South America
  "LA": "LATAM Airlines",
  "G3": "Gol Linhas",
  "AD": "Azul Airlines",
  "AV": "Avianca",
  "CM": "Copa Airlines",
  // Africa
  "ET": "Ethiopian Airlines",
  "SA": "South African Airways",
  "KQ": "Kenya Airways",
  "MS": "EgyptAir",
  "AT": "Royal Air Maroc",
};

export function getAirlineName(code: string): string {
  if (!code) return "Unknown";
  // Handle codes that might have underscores or extra chars from fli
  const clean = code.replace(/^_/, "").trim().toUpperCase();
  return AIRLINE_NAMES[clean] || code;
}
