export interface Airport {
  code: string;
  city: string;
  name: string;
  country: string;
}

export const POPULAR_AIRPORTS: Airport[] = [
  { code: "YEG", city: "Edmonton", name: "Edmonton Intl", country: "CA" },
  { code: "YYC", city: "Calgary", name: "Calgary Intl", country: "CA" },
  { code: "YVR", city: "Vancouver", name: "Vancouver Intl", country: "CA" },
  { code: "YYZ", city: "Toronto", name: "Toronto Pearson", country: "CA" },
  { code: "YUL", city: "Montreal", name: "Trudeau Intl", country: "CA" },
  { code: "YOW", city: "Ottawa", name: "Ottawa Intl", country: "CA" },
  { code: "YWG", city: "Winnipeg", name: "Winnipeg Intl", country: "CA" },
  { code: "YHZ", city: "Halifax", name: "Halifax Stanfield", country: "CA" },
  { code: "JFK", city: "New York", name: "John F. Kennedy", country: "US" },
  { code: "LGA", city: "New York", name: "LaGuardia", country: "US" },
  { code: "EWR", city: "Newark", name: "Newark Liberty", country: "US" },
  { code: "LAX", city: "Los Angeles", name: "Los Angeles Intl", country: "US" },
  { code: "SFO", city: "San Francisco", name: "San Francisco Intl", country: "US" },
  { code: "ORD", city: "Chicago", name: "O'Hare Intl", country: "US" },
  { code: "ATL", city: "Atlanta", name: "Hartsfield-Jackson", country: "US" },
  { code: "DFW", city: "Dallas", name: "Dallas/Fort Worth", country: "US" },
  { code: "DEN", city: "Denver", name: "Denver Intl", country: "US" },
  { code: "SEA", city: "Seattle", name: "Seattle-Tacoma", country: "US" },
  { code: "MIA", city: "Miami", name: "Miami Intl", country: "US" },
  { code: "BOS", city: "Boston", name: "Logan Intl", country: "US" },
  { code: "IAD", city: "Washington", name: "Dulles Intl", country: "US" },
  { code: "PHX", city: "Phoenix", name: "Sky Harbor", country: "US" },
  { code: "LAS", city: "Las Vegas", name: "Harry Reid Intl", country: "US" },
  { code: "MCO", city: "Orlando", name: "Orlando Intl", country: "US" },
  { code: "MSP", city: "Minneapolis", name: "Minneapolis-St Paul", country: "US" },
  { code: "DTW", city: "Detroit", name: "Detroit Metro", country: "US" },
  { code: "FLL", city: "Fort Lauderdale", name: "Fort Lauderdale Intl", country: "US" },
  { code: "PHL", city: "Philadelphia", name: "Philadelphia Intl", country: "US" },
  { code: "CLT", city: "Charlotte", name: "Charlotte Douglas", country: "US" },
  { code: "SAN", city: "San Diego", name: "San Diego Intl", country: "US" },
  { code: "HNL", city: "Honolulu", name: "Daniel K. Inouye", country: "US" },
  { code: "LHR", city: "London", name: "Heathrow", country: "GB" },
  { code: "LGW", city: "London", name: "Gatwick", country: "GB" },
  { code: "CDG", city: "Paris", name: "Charles de Gaulle", country: "FR" },
  { code: "AMS", city: "Amsterdam", name: "Schiphol", country: "NL" },
  { code: "FRA", city: "Frankfurt", name: "Frankfurt Main", country: "DE" },
  { code: "MAD", city: "Madrid", name: "Barajas", country: "ES" },
  { code: "BCN", city: "Barcelona", name: "El Prat", country: "ES" },
  { code: "FCO", city: "Rome", name: "Fiumicino", country: "IT" },
  { code: "MXP", city: "Milan", name: "Malpensa", country: "IT" },
  { code: "IST", city: "Istanbul", name: "Istanbul Airport", country: "TR" },
  { code: "DXB", city: "Dubai", name: "Dubai Intl", country: "AE" },
  { code: "SIN", city: "Singapore", name: "Changi", country: "SG" },
  { code: "HKG", city: "Hong Kong", name: "Hong Kong Intl", country: "HK" },
  { code: "NRT", city: "Tokyo", name: "Narita Intl", country: "JP" },
  { code: "HND", city: "Tokyo", name: "Haneda", country: "JP" },
  { code: "ICN", city: "Seoul", name: "Incheon Intl", country: "KR" },
  { code: "BKK", city: "Bangkok", name: "Suvarnabhumi", country: "TH" },
  { code: "SYD", city: "Sydney", name: "Kingsford Smith", country: "AU" },
  { code: "MEX", city: "Mexico City", name: "Benito Juarez", country: "MX" },
  { code: "CUN", city: "Cancun", name: "Cancun Intl", country: "MX" },
  { code: "GRU", city: "Sao Paulo", name: "Guarulhos", country: "BR" },
  { code: "LIS", city: "Lisbon", name: "Humberto Delgado", country: "PT" },
  { code: "VIE", city: "Vienna", name: "Vienna Intl", country: "AT" },
  { code: "ZRH", city: "Zurich", name: "Zurich Airport", country: "CH" },
  { code: "CPH", city: "Copenhagen", name: "Kastrup", country: "DK" },
  { code: "DUB", city: "Dublin", name: "Dublin Airport", country: "IE" },
  { code: "MUC", city: "Munich", name: "Munich Airport", country: "DE" },
  { code: "OSL", city: "Oslo", name: "Gardermoen", country: "NO" },
  { code: "ARN", city: "Stockholm", name: "Arlanda", country: "SE" },
];
