export interface Airport {
  code: string;
  city: string;
  name: string;
  country: string;
}

export const POPULAR_AIRPORTS: Airport[] = [
  // Canada
  { code: "YEG", city: "Edmonton", name: "Edmonton Intl", country: "CA" },
  { code: "YYC", city: "Calgary", name: "Calgary Intl", country: "CA" },
  { code: "YVR", city: "Vancouver", name: "Vancouver Intl", country: "CA" },
  { code: "YYZ", city: "Toronto", name: "Toronto Pearson", country: "CA" },
  { code: "YUL", city: "Montreal", name: "Trudeau Intl", country: "CA" },
  { code: "YOW", city: "Ottawa", name: "Ottawa Intl", country: "CA" },
  { code: "YWG", city: "Winnipeg", name: "Winnipeg Intl", country: "CA" },
  { code: "YHZ", city: "Halifax", name: "Halifax Stanfield", country: "CA" },
  { code: "YQB", city: "Quebec City", name: "Jean Lesage Intl", country: "CA" },
  { code: "YXE", city: "Saskatoon", name: "Saskatoon Diefenbaker", country: "CA" },
  { code: "YQR", city: "Regina", name: "Regina Intl", country: "CA" },
  { code: "YYJ", city: "Victoria", name: "Victoria Intl", country: "CA" },
  { code: "YXU", city: "London", name: "London Intl", country: "CA" },
  { code: "YKF", city: "Kitchener", name: "Region of Waterloo", country: "CA" },
  { code: "YLW", city: "Kelowna", name: "Kelowna Intl", country: "CA" },
  { code: "YQM", city: "Moncton", name: "Greater Moncton", country: "CA" },
  { code: "YYT", city: "St. John's", name: "St. John's Intl", country: "CA" },
  { code: "YZF", city: "Yellowknife", name: "Yellowknife Airport", country: "CA" },
  { code: "YXY", city: "Whitehorse", name: "Erik Nielsen Intl", country: "CA" },

  // United States - Major
  { code: "JFK", city: "New York", name: "John F. Kennedy", country: "US" },
  { code: "LGA", city: "New York", name: "LaGuardia", country: "US" },
  { code: "EWR", city: "Newark", name: "Newark Liberty", country: "US" },
  { code: "LAX", city: "Los Angeles", name: "Los Angeles Intl", country: "US" },
  { code: "SFO", city: "San Francisco", name: "San Francisco Intl", country: "US" },
  { code: "ORD", city: "Chicago", name: "O'Hare Intl", country: "US" },
  { code: "MDW", city: "Chicago", name: "Midway Intl", country: "US" },
  { code: "ATL", city: "Atlanta", name: "Hartsfield-Jackson", country: "US" },
  { code: "DFW", city: "Dallas", name: "Dallas/Fort Worth", country: "US" },
  { code: "DAL", city: "Dallas", name: "Love Field", country: "US" },
  { code: "DEN", city: "Denver", name: "Denver Intl", country: "US" },
  { code: "SEA", city: "Seattle", name: "Seattle-Tacoma", country: "US" },
  { code: "MIA", city: "Miami", name: "Miami Intl", country: "US" },
  { code: "FLL", city: "Fort Lauderdale", name: "Fort Lauderdale Intl", country: "US" },
  { code: "BOS", city: "Boston", name: "Logan Intl", country: "US" },
  { code: "IAD", city: "Washington", name: "Dulles Intl", country: "US" },
  { code: "DCA", city: "Washington", name: "Reagan National", country: "US" },
  { code: "BWI", city: "Baltimore", name: "Baltimore/Washington", country: "US" },
  { code: "PHX", city: "Phoenix", name: "Sky Harbor", country: "US" },
  { code: "LAS", city: "Las Vegas", name: "Harry Reid Intl", country: "US" },
  { code: "MCO", city: "Orlando", name: "Orlando Intl", country: "US" },
  { code: "TPA", city: "Tampa", name: "Tampa Intl", country: "US" },
  { code: "MSP", city: "Minneapolis", name: "Minneapolis-St Paul", country: "US" },
  { code: "DTW", city: "Detroit", name: "Detroit Metro", country: "US" },
  { code: "PHL", city: "Philadelphia", name: "Philadelphia Intl", country: "US" },
  { code: "CLT", city: "Charlotte", name: "Charlotte Douglas", country: "US" },
  { code: "SAN", city: "San Diego", name: "San Diego Intl", country: "US" },
  { code: "SLC", city: "Salt Lake City", name: "Salt Lake City Intl", country: "US" },
  { code: "IAH", city: "Houston", name: "George Bush Intl", country: "US" },
  { code: "HOU", city: "Houston", name: "Hobby", country: "US" },
  { code: "AUS", city: "Austin", name: "Austin-Bergstrom", country: "US" },
  { code: "SAT", city: "San Antonio", name: "San Antonio Intl", country: "US" },
  { code: "BNA", city: "Nashville", name: "Nashville Intl", country: "US" },
  { code: "RDU", city: "Raleigh", name: "Raleigh-Durham", country: "US" },
  { code: "PDX", city: "Portland", name: "Portland Intl", country: "US" },
  { code: "STL", city: "St. Louis", name: "Lambert Intl", country: "US" },
  { code: "MCI", city: "Kansas City", name: "Kansas City Intl", country: "US" },
  { code: "IND", city: "Indianapolis", name: "Indianapolis Intl", country: "US" },
  { code: "CLE", city: "Cleveland", name: "Cleveland Hopkins", country: "US" },
  { code: "CMH", city: "Columbus", name: "John Glenn Intl", country: "US" },
  { code: "PIT", city: "Pittsburgh", name: "Pittsburgh Intl", country: "US" },
  { code: "MKE", city: "Milwaukee", name: "Mitchell Intl", country: "US" },
  { code: "OAK", city: "Oakland", name: "Oakland Intl", country: "US" },
  { code: "SJC", city: "San Jose", name: "San Jose Intl", country: "US" },
  { code: "SMF", city: "Sacramento", name: "Sacramento Intl", country: "US" },
  { code: "HNL", city: "Honolulu", name: "Daniel K. Inouye", country: "US" },
  { code: "OGG", city: "Maui", name: "Kahului", country: "US" },
  { code: "ANC", city: "Anchorage", name: "Ted Stevens Intl", country: "US" },
  { code: "JAX", city: "Jacksonville", name: "Jacksonville Intl", country: "US" },
  { code: "RNO", city: "Reno", name: "Reno-Tahoe Intl", country: "US" },
  { code: "ABQ", city: "Albuquerque", name: "Albuquerque Intl", country: "US" },
  { code: "BUF", city: "Buffalo", name: "Buffalo Niagara", country: "US" },
  { code: "ONT", city: "Ontario", name: "Ontario Intl", country: "US" },
  { code: "BUR", city: "Burbank", name: "Hollywood Burbank", country: "US" },
  { code: "SNA", city: "Santa Ana", name: "John Wayne", country: "US" },

  // Mexico & Caribbean
  { code: "MEX", city: "Mexico City", name: "Benito Juarez", country: "MX" },
  { code: "CUN", city: "Cancun", name: "Cancun Intl", country: "MX" },
  { code: "GDL", city: "Guadalajara", name: "Miguel Hidalgo", country: "MX" },
  { code: "SJD", city: "Los Cabos", name: "San Jose del Cabo", country: "MX" },
  { code: "PVR", city: "Puerto Vallarta", name: "Gustavo Diaz Ordaz", country: "MX" },
  { code: "MBJ", city: "Montego Bay", name: "Sangster Intl", country: "JM" },
  { code: "PUJ", city: "Punta Cana", name: "Punta Cana Intl", country: "DO" },
  { code: "NAS", city: "Nassau", name: "Lynden Pindling", country: "BS" },
  { code: "SJU", city: "San Juan", name: "Luis Munoz Marin", country: "PR" },
  { code: "HAV", city: "Havana", name: "Jose Marti Intl", country: "CU" },

  // Europe - UK & Ireland
  { code: "LHR", city: "London", name: "Heathrow", country: "GB" },
  { code: "LGW", city: "London", name: "Gatwick", country: "GB" },
  { code: "STN", city: "London", name: "Stansted", country: "GB" },
  { code: "LTN", city: "London", name: "Luton", country: "GB" },
  { code: "MAN", city: "Manchester", name: "Manchester", country: "GB" },
  { code: "EDI", city: "Edinburgh", name: "Edinburgh", country: "GB" },
  { code: "BHX", city: "Birmingham", name: "Birmingham", country: "GB" },
  { code: "GLA", city: "Glasgow", name: "Glasgow", country: "GB" },
  { code: "DUB", city: "Dublin", name: "Dublin Airport", country: "IE" },

  // Europe - Western
  { code: "CDG", city: "Paris", name: "Charles de Gaulle", country: "FR" },
  { code: "ORY", city: "Paris", name: "Orly", country: "FR" },
  { code: "AMS", city: "Amsterdam", name: "Schiphol", country: "NL" },
  { code: "FRA", city: "Frankfurt", name: "Frankfurt Main", country: "DE" },
  { code: "MUC", city: "Munich", name: "Munich Airport", country: "DE" },
  { code: "BER", city: "Berlin", name: "Brandenburg", country: "DE" },
  { code: "ZRH", city: "Zurich", name: "Zurich Airport", country: "CH" },
  { code: "GVA", city: "Geneva", name: "Geneva Airport", country: "CH" },
  { code: "VIE", city: "Vienna", name: "Vienna Intl", country: "AT" },
  { code: "BRU", city: "Brussels", name: "Brussels Airport", country: "BE" },
  { code: "LIS", city: "Lisbon", name: "Humberto Delgado", country: "PT" },
  { code: "OPO", city: "Porto", name: "Francisco Sa Carneiro", country: "PT" },

  // Europe - Southern
  { code: "MAD", city: "Madrid", name: "Barajas", country: "ES" },
  { code: "BCN", city: "Barcelona", name: "El Prat", country: "ES" },
  { code: "AGP", city: "Malaga", name: "Costa del Sol", country: "ES" },
  { code: "PMI", city: "Palma", name: "Palma de Mallorca", country: "ES" },
  { code: "FCO", city: "Rome", name: "Fiumicino", country: "IT" },
  { code: "MXP", city: "Milan", name: "Malpensa", country: "IT" },
  { code: "VCE", city: "Venice", name: "Marco Polo", country: "IT" },
  { code: "NAP", city: "Naples", name: "Capodichino", country: "IT" },
  { code: "ATH", city: "Athens", name: "Eleftherios Venizelos", country: "GR" },
  { code: "IST", city: "Istanbul", name: "Istanbul Airport", country: "TR" },
  { code: "SAW", city: "Istanbul", name: "Sabiha Gokcen", country: "TR" },

  // Europe - Nordic
  { code: "CPH", city: "Copenhagen", name: "Kastrup", country: "DK" },
  { code: "OSL", city: "Oslo", name: "Gardermoen", country: "NO" },
  { code: "ARN", city: "Stockholm", name: "Arlanda", country: "SE" },
  { code: "HEL", city: "Helsinki", name: "Helsinki-Vantaa", country: "FI" },
  { code: "KEF", city: "Reykjavik", name: "Keflavik Intl", country: "IS" },

  // Europe - Eastern
  { code: "WAW", city: "Warsaw", name: "Chopin Airport", country: "PL" },
  { code: "PRG", city: "Prague", name: "Vaclav Havel", country: "CZ" },
  { code: "BUD", city: "Budapest", name: "Ferenc Liszt", country: "HU" },
  { code: "OTP", city: "Bucharest", name: "Henri Coanda", country: "RO" },
  { code: "ZAG", city: "Zagreb", name: "Franjo Tudman", country: "HR" },
  { code: "SPU", city: "Split", name: "Split Airport", country: "HR" },
  { code: "DBV", city: "Dubrovnik", name: "Dubrovnik Airport", country: "HR" },

  // Middle East
  { code: "DXB", city: "Dubai", name: "Dubai Intl", country: "AE" },
  { code: "AUH", city: "Abu Dhabi", name: "Zayed Intl", country: "AE" },
  { code: "DOH", city: "Doha", name: "Hamad Intl", country: "QA" },
  { code: "TLV", city: "Tel Aviv", name: "Ben Gurion", country: "IL" },
  { code: "AMM", city: "Amman", name: "Queen Alia", country: "JO" },
  { code: "RUH", city: "Riyadh", name: "King Khalid", country: "SA" },
  { code: "JED", city: "Jeddah", name: "King Abdulaziz", country: "SA" },

  // Asia
  { code: "SIN", city: "Singapore", name: "Changi", country: "SG" },
  { code: "HKG", city: "Hong Kong", name: "Hong Kong Intl", country: "HK" },
  { code: "NRT", city: "Tokyo", name: "Narita Intl", country: "JP" },
  { code: "HND", city: "Tokyo", name: "Haneda", country: "JP" },
  { code: "KIX", city: "Osaka", name: "Kansai Intl", country: "JP" },
  { code: "ICN", city: "Seoul", name: "Incheon Intl", country: "KR" },
  { code: "BKK", city: "Bangkok", name: "Suvarnabhumi", country: "TH" },
  { code: "KUL", city: "Kuala Lumpur", name: "KLIA", country: "MY" },
  { code: "MNL", city: "Manila", name: "Ninoy Aquino", country: "PH" },
  { code: "CGK", city: "Jakarta", name: "Soekarno-Hatta", country: "ID" },
  { code: "DPS", city: "Bali", name: "Ngurah Rai", country: "ID" },
  { code: "SGN", city: "Ho Chi Minh", name: "Tan Son Nhat", country: "VN" },
  { code: "HAN", city: "Hanoi", name: "Noi Bai", country: "VN" },
  { code: "PEK", city: "Beijing", name: "Capital Intl", country: "CN" },
  { code: "PVG", city: "Shanghai", name: "Pudong Intl", country: "CN" },
  { code: "DEL", city: "New Delhi", name: "Indira Gandhi", country: "IN" },
  { code: "BOM", city: "Mumbai", name: "Chhatrapati Shivaji", country: "IN" },
  { code: "BLR", city: "Bangalore", name: "Kempegowda", country: "IN" },
  { code: "TPE", city: "Taipei", name: "Taoyuan Intl", country: "TW" },
  { code: "CMB", city: "Colombo", name: "Bandaranaike", country: "LK" },

  // Oceania
  { code: "SYD", city: "Sydney", name: "Kingsford Smith", country: "AU" },
  { code: "MEL", city: "Melbourne", name: "Tullamarine", country: "AU" },
  { code: "BNE", city: "Brisbane", name: "Brisbane Airport", country: "AU" },
  { code: "PER", city: "Perth", name: "Perth Airport", country: "AU" },
  { code: "AKL", city: "Auckland", name: "Auckland Airport", country: "NZ" },
  { code: "CHC", city: "Christchurch", name: "Christchurch Intl", country: "NZ" },

  // South America
  { code: "GRU", city: "Sao Paulo", name: "Guarulhos", country: "BR" },
  { code: "GIG", city: "Rio de Janeiro", name: "Galeao", country: "BR" },
  { code: "EZE", city: "Buenos Aires", name: "Ministro Pistarini", country: "AR" },
  { code: "SCL", city: "Santiago", name: "Arturo Merino", country: "CL" },
  { code: "BOG", city: "Bogota", name: "El Dorado", country: "CO" },
  { code: "LIM", city: "Lima", name: "Jorge Chavez", country: "PE" },
  { code: "UIO", city: "Quito", name: "Mariscal Sucre", country: "EC" },

  // Africa
  { code: "JNB", city: "Johannesburg", name: "O.R. Tambo", country: "ZA" },
  { code: "CPT", city: "Cape Town", name: "Cape Town Intl", country: "ZA" },
  { code: "CAI", city: "Cairo", name: "Cairo Intl", country: "EG" },
  { code: "CMN", city: "Casablanca", name: "Mohammed V", country: "MA" },
  { code: "NBO", city: "Nairobi", name: "Jomo Kenyatta", country: "KE" },
  { code: "ADD", city: "Addis Ababa", name: "Bole Intl", country: "ET" },
  { code: "LOS", city: "Lagos", name: "Murtala Muhammed", country: "NG" },
  { code: "ACC", city: "Accra", name: "Kotoka Intl", country: "GH" },
];
